# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgAmZshyfBuA1hHONPN6ksVo0vPpY3pf
"""

import streamlit as st
import pandas as pd

st.set_page_config(layout-"wide")
st.title('Test Streamlit')

st.header('One")
st.header('Two', divider=True)

st.subheader('Three', divider True)
st.subheader('Four', divider=True)

st.text('Five)tSix(tSeven')
st.divider()