# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pa1K2YuHl_S9R48Es-_bg1hxYqEPpbO
"""

import streamlit as st
import random

st.set_page_config(layout="wide")
st.title("Test Streamlit")

con1 = st.container()
for col in con1.columns([1, 2, 3, 4], border=True):
    col.write("Hello World!")

con2 = st.container(height=100)
cc2_1, cc2_2, cc2_3 = con2.columns(3)
cc2_1.write("Column 5 @ Container 2")
cc2_2.write("Column 6 @ Container 2")
cc2_3.write("Column 7 @ Container 2")