# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2nMeHmm3EhIYE0Z9o8Gc-kFHOMb-SPC
"""

import random

st.set_page_config(layout="wide")
st.title("Test Streamlit")

st.write("Hello World!")

st.sidebar.title("Filter")
st.sidebar.header("Option")
st.sidebar.selectbox(
    "Pls Select One!",
    ('opt1', 'opt2', 'opt3')
)

with st.sidebar:
    st.radio(
        "Pls Choose One!",
        ('cho1', 'cho2', 'cho3'),
    )